[features]
seeds = false
[programs.localnet]
gh_action_scrects = "6zdDmuQg36ytdxeXYG6zoYdiiWVPXqao3Fvp2BbfV7o"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
