
name: solana anchor program upgrade

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  solana-anchor-program-upgrade:
    name: Run anchor upgrade
    runs-on: ubuntu-latest
#    container: projectserum/build:v0.25.0
    env:
      HOME: /root
      ENV_SECRET: ${{ secrets.MY_SECRET }}
      PROGRAM_FILEPATH: target/deploy/gh_action_scrects.so
      CLUSTER: testnet
      PROGRAM_ID: 6zdDmuQg36ytdxeXYG6zoYdiiWVPXqao3Fvp2BbfV7o

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Setup Yarn
#        run: yarn
#       - name: Setup wallet
#         run: echo ${{ secrets.SOLANA_KEYPAIR_JSON }} > $HOME/.config/solana/id.json
#       - name: Run anchor build
#         run: anchor build
#       - name: Run anchor upgrade to testnet
#         run: anchor upgrade $PROGRAM_FILEPATH --provider.cluster $CLUSTER --program-id $PROGRAM_ID
        
      - name: squads-multisig-program-upgrade
        uses: esemeniuc/container-template1@v0.0.5

# solana deploy
# create squad
# add managed program in ui
# set upgrade authority
# verify upgrade authority
# execute transaction

#==============================
# make changes + build new .so file
# write buffer
# solana program write-buffer --buffer-authority 53EBzzsNKEzGBxNMyqxj8iiTQvLLLMKTQs2scxx11fJb /home/eric/dev/solana-anchor-actions/target/deploy/starter_project.so
# create program upgrade in ui
# set the buffer authority
# verify buffer authority in ui
# send slack message to vote/(prior was to execute upgrade)
